version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8081:8081"

    environment:
      # Pass the local IP of your Llama.cpp instance here so python can talk to it
      - LLAMA_HOST=http://host.docker.internal:3000 
      - SEARXNG_HOST=http://host.docker.internal:4000 # Assuming searxng 
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:80"
    depends_on:
      - api
